apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: robot-role-binding
roleRef:
  kind: Role
  name: robot-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: robot-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: robot-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
