apiVersion: batch/v1
kind: Job
metadata:
  generateName: robot-framework-batchjob-
spec:
  template:
    spec:
      serviceAccountName: robot-account
      volumes:
        - name: cert
          secret:
            secretName: minio-crt
        - name: config
          configMap:
            name: robot-config
      restartPolicy: Never
      containers:
        - name: robot-framework-batchjob
          env:
            - name: SOURCE_FILE
              value: /config/config.yaml
            - name: WEBSITE_URL
              value: http://nginx-service:8080
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: root-user
                  name: minio
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: root-password
                  name: minio
          image: ghcr.io/johannessarpola/k8s-nginx-robottests:1.5
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: cert
              mountPath: "/certs/ca.crt"
              subPath: ca.crt
            - name: config
              mountPath: "/config/"
              readOnly: true
  backoffLimit: 0
  
