apiVersion: batch/v1
kind: CronJob
metadata:
  name: robot-framework-cronjob
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
      spec:
        serviceAccountName: robot-account
        template:
          spec:
            volumes:
              - name: cert
                secret:
                  secretName: minio-crt
              - name: config
                configMap:
                  name: robot-config
            restartPolicy: Never
            containers:
              - name: robot-framework-cronjob
                env:
                  - name: SOURCE_FILE
                    value: /config/config.yaml
                  - name: WEBSITE_URL
                    value: http://nginx-service:8080
                  - name: MINIO_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        key: root-user
                        name: minio
                  - name: MINIO_SECRET_KEY
                    valueFrom:
                      secretKeyRef:
                        key: root-password
                        name: minio
                image: ghcr.io/johannessarpola/k8s-nginx-robottests:1.3
                imagePullPolicy: IfNotPresent
                volumeMounts:
                  - name: cert
                    mountPath: "/certs/ca.crt"
                    subPath: ca.crt
                  - name: config
                    mountPath: "/config/"
                    readOnly: true